### ISSUE TITLE
Showing Black Screen in iOS 8.

### ISSUE THREAD

**Issue by ankur18sarda** [n1c/GlitchTest#1]
Hello,

You have developed very good Glitch app. It is working well on iOS 7 but when i am running it on iOS 8 it is showing black screen instead of glitch. Can you please check this issue & let me know how can i resolve this.

![glitchtestissue](https://cloud.githubusercontent.com/assets/4642295/5605352/cb8406d2-941b-11e4-8f42-0aae5b152a47.png)

**Comment by ankur18sarda** [comment]
Hi,

Any Update ?

**Comment by n1c** [comment]
Hey bud. So the whole reason I made this little repo is for [this apple dev forum post](https://devforums.apple.com/thread/232876) in which I'm asking Apple for some support / input on why this happens.

I haven't looked in to this in ages and have no idea how to fix it so I'll be closing the issue!
